### ISSUE TITLE
Tried adding new Stock ticker

### ISSUE THREAD

**Issue by darenr** [rlingineni/Scatter-Stocks#4]
Steps to reproduce: (tried latest FF/Chrome on Linux (Ubuntu)

- open example (works fine)
- remove DELL, add JNJ (or any other stock)
- get JS error:

```
graph.js:75 TypeError: Cannot read property '2. Symbol' of undefined
    at generateGraph (graph.js:44)
    at <anonymous>```

**Comment by rlingineni** [comment]
Alphavantage tends to throttle, so when the request fails, the response doesn't contain the necesary items. Thanks for opening an issue!
